name: CI B치sico

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v3

      - name: Simulaci칩n de validaci칩n
        run: echo Todo correcto. Archivos detectados:

      - name: Listar archivos del proyecto
        run: dir
